//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEventCalendar
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRoom
    {
        public int BookingId { get; set; }
        public int EmployeeNumber { get; set; }
        public int ClassRoomId { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime Endadate { get; set; }
        public System.TimeSpan Starttime { get; set; }
        public System.TimeSpan Endtime { get; set; }
        public string Reason { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual UserRegistrationDetail UserRegistrationDetail { get; set; }
    }
}
