//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEventCalendar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoomDetail
    {
        public int DetailsId { get; set; }
        public int ResourceId { get; set; }
        public int ResourceQuantity { get; set; }
        public int ClassroomId { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
