//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEventCalendar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public int EmployeeNumber { get; set; }
        public string Feedback1 { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    
        public virtual UserRegistrationDetail UserRegistrationDetail { get; set; }
    }
}
